spring.application.name=zonasriesgo
server.port=0

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.healthcheck.enabled=true
eureka.client.fetch-registry=true
spring.cloud.config.override-none=false

management.endpoints.web.exposure.include=*
management.endpoint.health.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

sre.weather.adapter=fake
